'use client';

import { useEffect, useState } from 'react';

type Settlement = { id:string; period_start:string; period_end:string; amount_received_usd:string; expected_usd:string|null; received_at:string|null };

export function AdminSettlementManager({ onChanged }: { onChanged: () => Promise<void> }) {
  const [items,setItems]=useState<Settlement[]>([]); const [start,setStart]=useState(''); const [end,setEnd]=useState(''); const [amount,setAmount]=useState(''); const [message,setMessage]=useState('');
  async function load(){const response=await fetch('/api/admin/settlements',{cache:'no-store'});if(response.ok)setItems((await response.json()).settlements);}
  useEffect(()=>{void load();},[]);
  async function submit(event:React.FormEvent){event.preventDefault();const response=await fetch('/api/admin/settlements',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({periodStart:start,periodEnd:end,amountReceivedUsd:Number(amount)})});const data=await response.json();setMessage(response.ok?'Settlement recorded.':data.error||'Unable to record settlement');if(response.ok){setAmount('');await Promise.all([load(),onChanged()]);}}
  return <section className="mt-8 rounded-2xl border border-default bg-surface p-6"><h2 className="text-xl font-semibold text-primary">Provider settlements</h2><p className="mt-2 text-sm text-secondary">Record cash only after it reaches the platform account. Expected balances do not reduce payout exposure.</p><form onSubmit={submit} className="mt-5 grid gap-3 md:grid-cols-4"><input type="date" required value={start} onChange={(event)=>setStart(event.target.value)} className="rounded-lg border border-default bg-surface-elevated px-3 py-2 text-sm text-primary"/><input type="date" required value={end} onChange={(event)=>setEnd(event.target.value)} className="rounded-lg border border-default bg-surface-elevated px-3 py-2 text-sm text-primary"/><input type="number" min="0" step="0.01" required placeholder="USD received" value={amount} onChange={(event)=>setAmount(event.target.value)} className="rounded-lg border border-default bg-surface-elevated px-3 py-2 text-sm text-primary"/><button className="rounded-lg bg-brand px-4 py-2 text-sm font-semibold text-background">Record receipt</button></form>{message&&<p className="mt-3 text-sm text-secondary">{message}</p>}<div className="mt-5 space-y-2">{items.slice(0,10).map((item)=><div key={item.id} className="flex justify-between rounded-lg bg-surface-elevated p-3 text-sm"><span className="text-secondary">{item.period_start} – {item.period_end}</span><span className="font-semibold text-primary">${Number(item.amount_received_usd).toFixed(2)}</span></div>)}{items.length===0&&<p className="text-sm text-muted">No provider cash receipts recorded.</p>}</div></section>;
}
