import Link from 'next/link';

export default function TermsPage() {
  return <main className="min-h-screen bg-background px-6 py-16 text-primary"><article className="mx-auto max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand">Beta terms · 12 September 2026</p><h1 className="mt-3 text-4xl font-bold">Attention Token beta terms</h1><div className="mt-8 space-y-7 text-sm leading-7 text-secondary">
    <section><h2 className="text-xl font-semibold text-primary">Eligibility</h2><p className="mt-2">The controlled beta is invitation-only and available to people who are at least 18 years old in supported locations. Availability of offers and payouts can vary by location.</p></section>
    <section><h2 className="text-xl font-semibold text-primary">Rewards</h2><p className="mt-2">Offerwall.GG confirms completed offers and supplies the credited amount. Rewards normally remain pending for seven days. Advertiser chargebacks, refunds, duplicate activity, or fraud findings may reverse a reward. A reversal can make an available balance negative, and future earnings first repay that balance.</p></section>
    <section><h2 className="text-xl font-semibold text-primary">SOL withdrawals</h2><p className="mt-2">One hundred credits equal one US dollar for withdrawal accounting. The SOL amount is fixed using a server-side quote when a request is accepted. Quotes expire after 15 minutes if the transaction is not signed. A correctly delivered blockchain transaction is final and cannot be recalled.</p></section>
    <section><h2 className="text-xl font-semibold text-primary">Reviews and restrictions</h2><p className="mt-2">We may pause or reject withdrawals when activity requires manual review, when platform payout capacity is full, or when an account violates provider or platform rules. Rejected unsigned requests receive their reserved credits back.</p></section>
    <section><h2 className="text-xl font-semibold text-primary">Support</h2><p className="mt-2">Offer tracking disputes should use the Offerwall support screen. Account and payout questions can be sent to <a className="text-brand" href="mailto:support@attentiontoken.net">support@attentiontoken.net</a>.</p></section>
  </div><Link href="/" className="mt-10 inline-flex text-sm font-semibold text-brand">← Return home</Link></article></main>;
}
